name: My First Action

on: push  # Runs when code is pushed

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # This checks out your repo
      
      - name: Print Hello World
        run: echo "Hello, GitHub Actions!"
      
      - name: Ping Google
        run: ping -c 4 google.com  # This pings google.com 4 times
